# Start AeroSpace at login
start-at-login = true

after-startup-command = [
  'exec-and-forget /opt/homebrew/opt/autoraise/bin/AutoRaise',
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0',
]

accordion-padding = 30
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 12
inner.vertical = 12
outer.left = 12
outer.bottom = 12
outer.top = 12
outer.right = 12

[workspace-to-monitor-force-assignment]
1 = 'Thunderbolt'
2 = 'Thunderbolt'
8 = 'DELL'
9 = 'DELL'

[mode.main.binding]
# Switch workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-left = 'workspace prev'
alt-right = 'workspace next'

# Focus window
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Focus monitor
alt-ctrl-1 = 'focus-monitor Thunderbolt'
alt-ctrl-2 = 'focus-monitor Built-in'
alt-ctrl-3 = 'focus-monitor DELL'
ctrl-left = 'focus-monitor --wrap-around prev'
ctrl-right = 'focus-monitor --wrap-around next'

# Move window
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Move window to workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-left = 'move-node-to-workspace prev'
alt-shift-right = 'move-node-to-workspace next'

# Move window to monitor
cmd-ctrl-1 = 'move-node-to-monitor --focus-follows-window Thunderbolt'
cmd-ctrl-2 = 'move-node-to-monitor --focus-follows-window Built-in'
cmd-ctrl-3 = 'move-node-to-monitor --focus-follows-window DELL'
cmd-ctrl-left = 'move-node-to-monitor --focus-follows-window prev'
cmd-ctrl-right = 'move-node-to-monitor --focus-follows-window next'

# Fullscreen window
alt-f = 'fullscreen'

# Toggle AeroSpace
alt-o = 'enable toggle'

# Toggle window float
alt-t = 'layout floating tiling'

# Toggle focus back-and-forth between last focused window
alt-q = 'focus-back-and-forth'

# Resize windows
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# Cycle through layouts
alt-slash = 'layout tiles horizontal vertical'
alt-period = 'layout accordion horizontal vertical'

# Rebalance windows
alt-comma = 'balance-sizes'

# Toggle focus back-and-forth between last focused workspace
alt-tab = 'workspace-back-and-forth'

# Move currently active workspace to the next monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Switch to service mode
alt-shift-backtick = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
