start-at-login = true

after-startup-command = [
  'exec-and-forget /opt/homebrew/opt/autoraise/bin/AutoRaise',
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0',
]

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 12
inner.vertical = 12
outer.left = 12
outer.bottom = 12
outer.top = 12
outer.right = 12

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 3'

# @TODO if setting window dimensions and layout is ever supported, these are 
# the dimensions for the windows on workspace 2
#
# HomeCam = {1416, 1238}
# Discord = {1416, 846}
# Messages = {702, 427}
# Spotify MiniPlayer = {702, 427}
[[on-window-detected]]
if.app-id = 'com.aaronpearce.Homecam'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
if.window-title-regex-substring = 'MiniPlayer'
run = ['layout tiling', 'move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.apple.Messages'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'move-node-to-workspace 5'
#
# Work computer
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
if.window-title-regex-substring = '^Spotify$'
run = 'move-node-to-workspace 6'

# Work computer
[[on-window-detected]]
if.app-id = 'com.f5networks.EdgeClient'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.electron.dockerdesktop'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[workspace-to-monitor-force-assignment]
4 = ['Thunderbolt', 'secondary']
5 = ['Thunderbolt', 'secondary']
3 = ['DELL', 'main']

[mode.main.binding]
# Focus workspace
alt-1 = 'workspace 1'         # Notes
alt-2 = 'workspace 2'         # Browser
alt-3 = 'workspace 3'         # Terminal
alt-4 = 'workspace 4'         # Chats + [Security Cameras + Mini Music]
alt-5 = 'workspace 5'         # Mail + Calendar + [Slack @ Work]
alt-6 = 'workspace 6'         # Music
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
ctrl-left = 'workspace prev'
ctrl-right = 'workspace next'

# Focus window
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Focus monitor
alt-ctrl-1 = 'focus-monitor Thunderbolt'
alt-ctrl-2 = 'focus-monitor Built-in'
alt-ctrl-3 = 'focus-monitor DELL'
alt-left = 'focus-monitor --wrap-around prev'
alt-right = 'focus-monitor --wrap-around next'

# Move window
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Join window
alt-ctrl-h = 'join-with left'
alt-ctrl-j = 'join-with down'
alt-ctrl-k = 'join-with up'
alt-ctrl-l = 'join-with right'

# Move window to workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-left = 'move-node-to-workspace prev'
alt-shift-right = 'move-node-to-workspace next'

# Move window to monitor
cmd-ctrl-1 = 'move-node-to-monitor --focus-follows-window Thunderbolt'
cmd-ctrl-2 = 'move-node-to-monitor --focus-follows-window Built-in'
cmd-ctrl-3 = 'move-node-to-monitor --focus-follows-window DELL'
cmd-ctrl-left = 'move-node-to-monitor --focus-follows-window prev'
cmd-ctrl-right = 'move-node-to-monitor --focus-follows-window next'

# Fullscreen window
alt-f = 'fullscreen'

# Toggle window float
alt-t = 'layout floating tiling'

# Toggle focus back-and-forth between last focused window
alt-q = 'focus-back-and-forth'

# Resize windows
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
alt-shift-backslash = 'balance-sizes'

# Cycle through layouts
alt-period = 'layout tiles horizontal vertical'
alt-slash = 'layout accordion horizontal vertical'

# Toggle focus back-and-forth between last focused workspace
alt-tab = 'workspace-back-and-forth'

# Move currently active workspace to the next monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Switch to service mode
alt-shift-backtick = 'mode service'

[mode.service.binding]
# Reload config
esc = ['reload-config', 'mode main']

# Reset layout in workspace
r = ['flatten-workspace-tree', 'mode main']

# Close all windows but current in current workspace
backspace = ['close-all-windows-but-current', 'mode main']

# Toggle AeroSpace
a = 'enable toggle'
