#!/bin/bash

function widget_should_display {
  echo true
}

function widget {
  WORKED=$(timetrap today -fjira | tail -n1 | awk '{print $2}' | cut -d ":" -f 1,2)
  HOURS=$(echo $WORKED | cut -d ":" -f 1)
  MINUTES=$(echo $WORKED | cut -d ":" -f 2)
  CLOCK=$(perl -C -e 'print chr 0xf017')

  case $MINUTES in
    "15")
      MINUTES=".25"
      ;;
    "30")
      MINUTES=".5"
      ;;
    "45")
      MINUTES=".75"
      ;;
    *)
      MINUTES=""
      ;;
  esac

  WORKED="${HOURS}${MINUTES}/8"

  echo "#[fg=colour33,bold]$CLOCK #[fg=colour2,nobold]$WORKED"
}
