---
database_file: /Users/marc/.timetrap.db
round_in_seconds: 900
append_notes_delimiter: ' '
formatter_search_paths:
- /Users/marc/.timetrap/formatters
default_formatter: text
auto_sheet: dotfiles
auto_sheet_search_paths:
- /Users/marc/.timetrap/auto_sheets
default_command: 
auto_checkout: false
require_note: true
