import '~/dotfiles/just/common.just'

# dotfiles functionality
mod dotfiles '~/dotfiles/just/dotfiles.just'

# Visual Regression Testing
mod vrt '~/dotfiles/just/vrt.just'

# Display this list of available commands
@list:
    just -g --list

# Edit the global justfile
@edit:
    $EDITOR "{{ justfile() }}"

# Conditionally import the work.just file if we're on my work computer
import? '/Users/maddeo/dotfiles/just/work.just'
