#!/bin/bash
## This script is intended to bootstrap a freshly installed copy of OS X to get
## up and running with my development environment
##
## Tested on OS X 10.11 El Capitan

## Install software

# Install Xcode Command Line Tools
xcode-select --install

# Install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Tap homebrew/dupes
brew tap homebrew/dupes

# Get the latest git
brew install git

# Install Zsh
brew install zsh
echo $(which zsh) | sudo tee -a /etc/shells; chsh -s $(which zsh)

# Install the gnu coreutils so we can use dircolors as gdircolors
brew install coreutils

## Install applications

# Install homebrew cask
brew install caskroom/cask/brew-cask

## Set sensible osx defaults

# Remove the [ mark from the terminal
defaults write com.apple.Terminal AutoMarkPromptLines -int 0

## Clone and install dotfiles

# Clone my dotfiles
git clone --recursive https://github.com/marcaddeo/dotfiles.git $HOME/dotfiles

# Install dotfiles
$HOME/dotfiles/script/install
