#!/bin/bash
DOTFILES="$HOME/dotfiles"

# Zsh
ln -sf $DOTFILES/zsh/.oh-my-zsh $HOME
ln -sf $DOTFILES/zsh/.zshrc $HOME

# Git
ln -sf $DOTFILES/git/.gitconfig $HOME
ln -sf $DOTFILES/git/.gitignore $HOME

# Fonts
ln -sf $DOTFILES/fonts/InconsolataForPowerlinePlusNerdFileTypesMonoPlusFontAwesomePlusOcticonsPlusPomicons.otf \
    $HOME/Library/Fonts

# Neovim
ln -sf $DOTFILES/neovim/.nvim $HOME
ln -sf $DOTFILES/neovim/.nvimrc $HOME

# Tmux
ln -sf $DOTFILES/tmux/.tmux.conf $HOME

# T
ln -sf $DOTFILES/tasks $HOME

# SSH
ln -sf $DOTFILES/ssh/config $HOME/.ssh

# Gnupg
ln -sf $DOTFILES/gnupg/gpg.conf $HOME/.gnupg
ln -sf $DOTFILES/gnupg/gpg-agent.conf $HOME/.gnupg

# Timetrap
ln -sf $DOTFILES/timetrap/.timetrap.yml $HOME
ln -sf $DOTFILES/timetrap/.timetrap.db $HOME

# Terminal
ln -sf $DOTFILES/terminal/.xterm-256color.ti $HOME
ln -sf $DOTFILES/terminal/.screen-256color.ti $HOME
cp $DOTFILES/terminal/com.apple.Terminal.plist $HOME/Library/Preferences
defaults read com.apple.Terminal >/dev/null 2>&1
