#!/bin/bash
DOTFILES="$HOME/dotfiles"

# Zsh
ln -sf $DOTFILES/zsh/.oh-my-zsh $HOME
ln -sf $DOTFILES/zsh/.zshrc $HOME

# Git
ln -sf $DOTFILES/git/.gitconfig $HOME
ln -sf $DOTFILES/git/.gitignore $HOME

# Ag
ln -sf $DOTGILES/ag/.agignore $HOME

# Fonts
cp $DOTFILES/fonts/InconsolataForPowerlinePlusNerdFileTypesMonoPlusFontAwesomePlusOcticonsPlusPomicons.otf \
    $HOME/Library/Fonts

# Neovim
ln -sf $DOTFILES/neovim/.nvim $HOME
ln -sf $DOTFILES/neovim/.nvimrc $HOME

# Tmux
ln -sf $DOTFILES/tmux/.tmux.conf $HOME
mkdir -p $HOME/.tmux/plugins
ln -sf $DOTFILES/tmux/tpm $HOME/.tmux/plugins

# SSH
ln -sf $DOTFILES/ssh/config $HOME/.ssh

# Decrypt and copy ssh keys
keybase decrypt -S marcaddeo -o $HOME/.ssh/id_rsa.github $DOTFILES/ssh/id_rsa.github.asc
keybase decrypt -S marcaddeo -o $HOME/.ssh/id_rsa.acquia $DOTFILES/ssh/id_rsa.acquia.asc

# Chmod the keys
chmod 600 $HOME/.ssh/id_rsa.github
chmod 600 $HOME/.ssh/id_rsa.acquia

# Generate public keys from the private keys
ssh-keygen -y -f $HOME/.ssh/id_rsa.github > $HOME/.ssh/id_rsa.github.pub
ssh-keygen -y -f $HOME/.ssh/id_rsa.acquia > $HOME/.ssh/id_rsa.acquia.pub

# Gnupg
ln -sf $DOTFILES/gnupg/gpg.conf $HOME/.gnupg
ln -sf $DOTFILES/gnupg/gpg-agent.conf $HOME/.gnupg

# Timetrap
ln -sf $DOTFILES/timetrap/.timetrap.yml $HOME
keybase decrypt -S marcaddeo -o $DOTFILES/timetrap/.timetrap-to-jira.json \
    $DOTFILES/timetrap/.timetrap-to-jira.json.asc
ln -sf $DOTFILES/timetrap/.timetrap-to-jira.json $HOME

# Terminal
ln -sf $DOTFILES/terminal/.xterm-256color.ti $HOME
ln -sf $DOTFILES/terminal/.screen-256color.ti $HOME
cp $DOTFILES/terminal/com.apple.Terminal.plist $HOME/Library/Preferences
defaults read com.apple.Terminal >/dev/null 2>&1
