#!/bin/bash
DOTFILES="$HOME/dotfiles"

# Zsh
ln -sf $DOTFILES/zsh/.oh-my-zsh $HOME
ln -sf $DOTFILES/zsh/.zshrc $HOME

# Git
ln -sf $DOTFILES/git/.gitconfig $HOME
ln -sf $DOTFILES/git/.gitignore $HOME

# Fonts
ln -sf $DOTFILES/fonts/InconsolataForPowerlinePlusNerdFileTypesMonoPlusFontAwesomePlusOcticonsPlusPomicons.otf \
    $HOME/Library/Fonts

# Neovim
ln -sf $DOTFILES/neovim/.nvim $HOME
ln -sf $DOTFILES/neovim/.nvimrc $HOME

# Tmux
ln -sf $DOTFILES/tmux/.tmux.conf $HOME

# Terminal
ln -sf $DOTFILES/terminal/com.apple.Terminal.plist $HOME/Library/Preferences
defaults read com.apple.Terminal >/dev/null 2>&1
