#!/bin/bash
SCRIPT=$HOME/dotfiles/script
#MPD_PLAYING=$(mpc | grep playing)

#if [[ ! -z $MPD_PLAYING ]]; then
    #echo $(mpc current --format "%title% by %artist%")
    #exit;
#else
    SPOTIFY=$(osascript $SCRIPT/spotify.scpt)
#fi

if [[ ! -z $SPOTIFY ]]; then
    echo $SPOTIFY
    exit;
else
    ITUNES=$(osascript $SCRIPT/itunes.scpt)
fi

if [[ ! -z $ITUNES ]]; then
    echo $ITUNES
    exit;
else
    SONOS=$(socos list | grep "Open Space" | cut -d ' ' -f2 | xargs socos current)
fi

if [[ ! -z $SONOS ]]; then
    # Using a modified SoCos so that it returns json
    ARTIST=$(echo $SONOS | jq -r '.artist')
    TITLE=$(echo $SONOS | jq -r '.title')

    echo "$TITLE by $ARTIST"
    exit;
fi

echo "nothing playing"
