#!/bin/bash
BOLD="\033[1m"
RESET="\033[0m"
GREEN="\033[0;32m"
ORANGE="\033[0;33m"
COLOR="\033[0;34m"
INVISIBLE="\033[8m"
I=$INVISIBLE
R=$RESET

printf "\n\n"
printf "${I}'''''''''''''''''''''''''''${R}${COLOR}.-/+osyhddmmmmmmddhyso+/-.${I}'''''''''''''''''''''''''''${R}${COLOR}\n"
printf "${I}''''''''''''''''''''''${R}${COLOR}.:+yhmmmmmmmmmmmmmmmmmmmmmmmmmmdy+:.${I}''''''''''''''''''''''${R}${COLOR}\n"
printf "${I}'''''''''''''''''''${R}${COLOR}-+ymmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmyo-${I}'''''''''''''''''''${R}${COLOR}\n"
printf "${I}''''''''''''''''${R}${COLOR}-odmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdo-${I}''''''''''''''''${R}${COLOR}\n"
printf "${I}'''''''''''''${R}${COLOR}.+hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmh+.${I}'''''''''''''${R}${COLOR}\n"
printf "${I}'''''''''''${R}${COLOR}.ommmmmmmmmmmmmmmmmmmmmmmddhhhhddmmmmmmmmmmmmmmmmmmmmmmmo.${I}'''''''''''${R}${COLOR}\n"
printf "${I}'''''''''${R}${COLOR}.ommmmmmmmmmmmmmmmmmhs+/-.${I}''''''''''${R}${COLOR}.-/+shmmmmmmmmmmmmmmmmmmo.${I}'''''''''${R}${COLOR}\n"
printf "${I}''''''''${R}${COLOR}/dmmmmmmmmmmmmmmmho:.${I}''''''''''''''''''''''${R}${COLOR}.:ohmmmmmmmmmmmmmmmd/${I}''''''''${R}${COLOR}\n"
printf "${I}''''''${R}${COLOR}.ymmmmmmmmmmmmmmh+-${I}''''''''''''''''''''''''''''''${R}${COLOR}-+hmmmmmmmmmmmmmmy.${I}''''''${R}${COLOR}\n"
printf "${I}'''''${R}${COLOR}-dmmmmmmmmmmmmmy:${I}''''''''''''''''''''''''''''''''''''${R}${COLOR}:ymmmmmmmmmmmmmd-${I}'''''${R}${COLOR}\n"
printf "${I}''''${R}${COLOR}:mmmmmmmmmmmmmy-${I}''''''''''''''''''''${R}${COLOR}ymmmmd+${I}'''''''''''''${R}${COLOR}:ymmmmmmmmmmmmm:${I}''''${R}${COLOR}\n"
printf "${I}'''${R}${COLOR}:mmmmmmmmmmmmd/${I}''''''''''''''''''''''${R}${COLOR}mmmmmmy${I}'''''''''''''''${R}${COLOR}/dmmmmmmmmmmmm:${I}'''${R}${COLOR}\n"
printf "${I}''${R}${COLOR}-mmmmmmmmmmmmh-${I}'''''''''''''''''''''''${R}${COLOR}mmmmmmy${I}''''''''''''''''${R}${COLOR}-hmmmmmmmmmmmd-${I}''${R}${COLOR}\n"
printf "${I}'${R}${COLOR}.hmmmmmmmmmmmy.${I}''''''''''''''''''''''''${R}${COLOR}mmmmmmy${I}'''''''''''''''''${R}${COLOR}.ymmmmmmmmmmmh.${I}'${R}${COLOR}\n"
printf "${I}'${R}${COLOR}ommmmmmmmmmmh.${I}'''''''''''''''''''''''''${R}${COLOR}mmmmmmy${I}''''''''''''''''''${R}${COLOR}.hmmmmmmmmmmmo${I}'${R}${COLOR}\n"
printf ".dmmmmmmmmmmm-${I}''''''''''''''''''''''''''${R}${COLOR}mmmmmmy${I}'''''''''''''''''''${R}${COLOR}-mmmmmmmmmmmd:\n"
printf "+mmmmmmmmmmmo${I}'''''''''''''''''''''''''''${R}${COLOR}mmmmmmy${I}''''''''''''''''''''${R}${COLOR}ommmmmmmmmmmd\n"
printf "ymmmmmmmmmmm.${I}'''''''''''''''''''''''''''${R}${COLOR}mmmmmmy${I}''''''''''''''''''''${R}${COLOR}-mmmmmmmmmmmm\n"
printf "dmmmmmmmmmmh${I}''''''''''''''''''''''''''''${R}${COLOR}mmmmmmy${I}'''''''''''''''''''''${R}${COLOR}hmmmmmmmmmmm\n"
printf "mmmmmmmmmmmy${I}''''''''''''''''''''''''''''${R}${COLOR}mmmmmmy${I}'''''''''''''''''''''${R}${COLOR}ymmmmmmmmmmm\n"
printf "mmmmmmmmmmmy${I}''''''''''''''${R}${COLOR}-dmmmmmmmmmmmmmmmmmmy${I}'''''''''''''''''''''${R}${COLOR}ymmmmmmmmmmm\n"
printf "dmmmmmmmmmmh${I}''''''''''''''${R}${COLOR}/mmmmmmmmmmmmmmmmmmmy${I}'''''''''''''''''''''${R}${COLOR}hmmmmmmmmmmm\n"
printf "ymmmmmmmmmmm-${I}'''''''''''''${R}${COLOR}:mmmmmmmmmmmmmmmmmmms${I}''''''''''''''''''''${R}${COLOR}-mmmmmmmmmmmm\n"
printf "+mmmmmmmmmmmo${I}''''''''''''''${R}${COLOR}-/////////////////:.${I}''''''''''''''''''''${R}${COLOR}ommmmmmmmmmmm\n"
printf ".dmmmmmmmmmmm-${I}''''''''''''''''''''''''''''''''''''''''''''''''''''${R}${COLOR}-mmmmmmmmmmmd:${I}'${R}${COLOR}\n"
printf "${I}'${R}${COLOR}ommmmmmmmmmmh.${I}''''''''''''''''''''''''''''''''''''''''''''''''''${R}${COLOR}.hmmmmmmmmmmmo${I}'${R}${COLOR}\n"
printf "${I}'${R}${COLOR}.hmmmmmmmmmmmh.${I}''''''''''''''''''''''''''''''''''''''''''''''''${R}${COLOR}.hmmmmmmmmmmmh.${I}'${R}${COLOR}\n"
printf "${I}''${R}${COLOR}-mmmmmmmmmmmmh-${I}''''''''''''''''''''''''''''''''''''''''''''''${R}${COLOR}-hmmmmmmmmmmmm-${I}''${R}${COLOR}\n"
printf "${I}'''${R}${COLOR}:mmmmmmmmmmmmm+${I}''''''''''''''''''''''''''''''''''''''''''''${R}${COLOR}+mmmmmmmmmmmmm:${I}'''${R}${COLOR}\n"
printf "${I}''''${R}${COLOR}:mmmmmmmmmmmmmh:${I}''''''''''''''''''''''''''''''''''''''''${R}${COLOR}:hmmmmmmmmmmmmm:${I}''''${R}${COLOR}\n"
printf "${I}'''''${R}${COLOR}-dmmmmmmmmmmmmmy:${I}''''''''''''''''''''''''''''''''''''${R}${COLOR}:ymmmmmmmmmmmmmd-${I}'''''${R}${COLOR}\n"
printf "${I}''''''${R}${COLOR}.ymmmmmmmmmmmmmmdo-${I}''''''''''''''''''''''''''''''${R}${COLOR}-odmmmmmmmmmmmmmms.${I}''''''${R}${COLOR}\n"
printf "${I}''''''''${R}${COLOR}/dmmmmmmmmmmmmmmmho:.${I}''''''''''''''''''''''${R}${COLOR}.:ohmmmmmmmmmmmmmmmd/${I}''''''''${R}${COLOR}\n"
printf "${I}'''''''''${R}${COLOR}.ommmmmmmmmmmmmmmmmmhso/:..${I}''''''''${R}${COLOR}..:/oshmmmmmmmmmmmmmmmmmmo.${I}'''''''''${R}${COLOR}\n"
printf "${I}'''''''''''${R}${COLOR}.odmmmmmmmmmmmmmmmmmmmmmmdddhhdddmmmmmmmmmmmmmmmmmmmmmmdo.${I}'''''''''''${R}${COLOR}\n"
printf "${I}'''''''''''''${R}${COLOR}.+hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmh+.${I}'''''''''''''${R}${COLOR}\n"
printf "${I}''''''''''''''''${R}${COLOR}-odmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdo-${I}''''''''''''''''${R}${COLOR}\n"
printf "${I}'''''''''''''''''''${R}${COLOR}-+ymmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmy+-${I}'''''''''''''''''''${R}${COLOR}\n"
printf "${I}''''''''''''''''''''''${R}${COLOR}.:+shmmmmmmmmmmmmmmmmmmmmmmmmmmhs+:.${I}''''''''''''''''''''''${R}${COLOR}\n"
printf "${I}''''''''''''''''''''''''''''${R}${COLOR}-/+osyhddmmmmmmddhyso+/-.${I}'''''''''''''''''''''''''''${R}${COLOR}\n"
printf "\n\n"

function refresh_tmux {
    tmux refresh-client -S
}
trap refresh_tmux EXIT

function display_time() {
    local T=$1
    local D=$((T/60/60/24))
    local H=$((T/60/60%24))
    local M=$((T/60%60))
    local S=$((T%60))
    [[ $D > 0 ]] && printf '%d days ' $D
    [[ $H > 0 ]] && printf '%d hours ' $H
    [[ $M > 0 ]] && printf '%d minutes ' $M
    [[ $D > 0 || $H > 0 || $M > 0 ]] && printf 'and '
    printf '%d seconds\n' $S
}

NOW=$(date "+%s")
IDLE_SINCE=$(($NOW - $1))
IDLE_SINCE="$(date -r$IDLE_SINCE "+%T")"
IDLE_TIME=$(display_time $1)

PS3="> "
options=(
    "Keep idle time"
    "Discard idle time"
    "Discard idle time and continue"
    "Add idle time as a new time entry"
)
printf "${ORANGE}You have been idle since$RESET ${BOLD}$IDLE_SINCE$RESET $ORANGE(${GREEN}$IDLE_TIME$RESET$ORANGE)$RESET\n"
select opt in "${options[@]}"; do
    case $opt in
        "Keep idle time")
            echo "Keeping idle time..."
            sleep 1
            exit
            ;;
        "Discard idle time")
            echo "Discarding idle time..."
            sleep 1
            timetrap out --at "$IDLE_SINCE"
            exit
            ;;
        "Discard idle time and continue")
            echo "Discarding idle time and continuing..."
            sleep 1
            timetrap out --at "$IDLE_SINCE"
            timetrap resume
            exit
            ;;
        "Add idle time as a new time entry")
            echo "Adding idle time as a new time entry..."
            sleep 1
            timetrap out --at "$IDLE_SINCE"
            timetrap in --at "$IDLE_SINCE"
            exit
            ;;
        *) echo "Invalid option";;
    esac
done
