#!/bin/bash -ex
NOW=$(timetrap now 2>&1)
CLOCK=$(perl -C -e 'print chr 0xf017')
IDLE_MINIMUM=300
ACTIVE_MAX=20
IDLE_FILE=~/.ti-idle
IDLE_SCRIPT=~/dotfiles/script/ti-idle

if [[ $NOW != *"not running"* ]]; then
	typeset -i IDLE=$((`ioreg -c IOHIDSystem | sed -e '/HIDIdleTime/ !{ d' -e 't' -e '}' -e 's/.* = //g' -e 'q'` / 1000000000))

	TIME=$(echo $NOW | perl -Mutf8 -CS -p -e 's/^.*?:\s([\d:]+)\s\((.*)\)/$1/')
	NOTE=$(echo $NOW | perl -Mutf8 -CS -p -e 's/^.*?:\s([\d:]+)\s\((.*)\)/$2/')

	if [[ -f $IDLE_FILE ]]; then
		typeset -i IDLE_ON_FILE=`cat $IDLE_FILE`
	else
		IDLE_ON_FILE=0
	fi

	echo $IDLE > $IDLE_FILE

	if (( $IDLE_ON_FILE > $IDLE_MINIMUM && $IDLE < $ACTIVE_MAX )); then
		echo 0 > $IDLE_FILE
		tmux new-window -n "Idle Time" "$IDLE_SCRIPT $IDLE_ON_FILE"
	fi

	if (( ${#NOTE} > 20 )); then
		NOTE="$(echo $NOTE | cut -c 1-20) …"
	fi

	echo "#[fg=colour33,bold]$CLOCK #[fg=colour2,nobold]$TIME $NOTE #[default] :: "
else
	echo "#[bold]$CLOCK #[fg=colour10,nobold]idle #[default]::"
fi
