#!/bin/bash

function widget_should_display {
  local system_profiler
  local mac_addr
  local connected

  system_profiler="$(system_profiler SPBluetoothDataType)"
  mac_addr="$(grep -b2 "Minor Type: Headphones"<<< "$system_profiler" | awk '/Address/{print $3}')"
  connected="$(grep -ia6 "$mac_addr" <<< "$system_profiler" | awk '/Connected: Yes/{print 1}')"

  if [[ "$connected" ]]; then
    echo true
  else
    echo false
  fi
}

function widget {
  local output
  local battery_levels
  local system_profiler
  local mac_addr
  local bluetooh_data
  local bluetooh_defaults

  output=()
  battery_levels=(
    "BatteryPercentCombined"
    "HeadsetBattery"
    "BatteryPercentSingle"
    "BatteryPercentCase"
    "BatteryPercentLeft"
    "BatteryPercentRight"
  )
  system_profiler="$(system_profiler SPBluetoothDataType)"
  mac_addr="$(grep -b2 "Minor Type: Headphones"<<< "$system_profiler" | awk '/Address/{print $3}')"
  bluetooth_defaults="$(defaults read /Library/Preferences/com.apple.Bluetooth)"
  bluetooth_data="$(grep -ia6 '"'"$mac_addr"'"' <<< "$bluetooth_defaults")"

  for level in "${battery_levels[@]}"; do
    declare -x "${level}"="$(awk -v pat="${level}" '$0~pat{gsub (";",""); print $3 }' <<< "$bluetooth_data")"
    if [[ ! -z "${!level}" ]]; then
      output+=("$(awk '/BatteryPercent/{print substr($0,15,1)": "}' <<< "${level}")${!level}%")
    fi
  done

  echo "${output[*]}"
}
