#!/bin/bash

function widget_should_display {
  echo true
}

function widget {
  NOW=$(timetrap now 2>&1)

  if [[ $NOW != *"not running"* ]]; then
    TIME=$(echo $NOW | perl -Mutf8 -CS -p -e 's/^.*?:\s([\d:]+)\s\((.*)\)/$1/')
    NOTE=$(echo $NOW | perl -Mutf8 -CS -p -e 's/^.*?:\s([\d:]+)\s\((.*)\)/$2/')

    if (( ${#NOTE} > 20 )); then
      NOTE="$(echo $NOTE | cut -c 1-20) …"
    fi

    echo "$TIME $NOTE"
  else
    echo "idle"
  fi
}
