return {
  "JoosepAlviste/nvim-ts-context-commentstring",

  {
    "nvim-treesitter/nvim-treesitter",
    version = false,
    build = ":TSUpdate",
    event = "BufReadPost",
    opts = {
      autotag = {
        enable = true,
        filetypes = {
          "css",
          "scss",
          "html",
          "javascript",
          "typescript",
          "javascriptreact",
          "typescriptreact",
          "just",
          "svelte",
          "vue",
          "tsx",
          "jsx",
          "rescript",
          "xml",
          "php",
          "markdown",
          "glimmer",
          "handlebars",
          "hbs",
          "htmldjango",
          "html.twig",
          "twig"
        },
      },
      endwise = { enable = true },
      highlight = {
        enable = true,
        -- Twig highlighting doesn't support html.twig properly, so for now
        -- i'm just disable it
        disable = { "twig" },
      },
      indent = { enable = true },
      context_commentstring = { enable = true },
      ensure_installed = {
        "awk",
        "bash",
        "comment",
        "css",
        "dockerfile",
        "elixir",
        "erlang",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "graphql",
        "html",
        "javascript",
        "json",
        "json5",
        "jq",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "php",
        "phpdoc",
        "python",
        "query",
        "regex",
        "ruby",
        "rust",
        "sql",
        "svelte",
        "toml",
        "tsx",
        "typescript",
        "twig",
        "vim",
        "vue",
        "yaml",
      },
    },
    dependencies = {
      "windwp/nvim-ts-autotag",
      "RRethy/nvim-treesitter-endwise",
      "JoosepAlviste/nvim-ts-context-commentstring",
      "IndianBoy42/tree-sitter-just"
    },
    config = function(_, opts)
      require("nvim-treesitter.configs").setup(opts)
      require("tree-sitter-just").setup({})

      vim.treesitter.language.register("twig", "html.twig");
    end,
  },
}
