return {
	{ "JoosepAlviste/nvim-ts-context-commentstring", config = true },

	{
		"nvim-treesitter/nvim-treesitter",
		version = false,
		build = ":TSUpdate",
		event = "BufReadPost",
		opts = {
			autotag = {
				enable = true,
				filetypes = {
					"css",
					"scss",
					"html",
					"javascript",
					"typescript",
					"javascriptreact",
					"typescriptreact",
					"svelte",
					"vue",
					"tsx",
					"jsx",
					"rescript",
					"xml",
					"php",
					"markdown",
					"glimmer",
					"handlebars",
					"hbs",
					"htmldjango",
					"html.twig",
					"twig",
				},
			},
			endwise = { enable = true },
			highlight = {
				enable = true,
				-- Twig highlighting doesn't support html.twig properly, so for now
				-- i'm just disable it
				disable = { "twig" },
			},
			indent = { enable = true },
			ensure_installed = {
				"awk",
				"bash",
				"comment",
				"css",
				"dockerfile",
				"elixir",
				"erlang",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"go",
				"graphql",
				"help",
				"html",
				"javascript",
				"json",
				"json5",
				"jq",
				"just",
				"lua",
				"make",
				"markdown",
				"markdown_inline",
				"php",
				"phpdoc",
				"python",
				"query",
				"regex",
				"ruby",
				"rust",
				"sql",
				"svelte",
				"toml",
				"tsx",
				"typescript",
				"twig",
				"vim",
				"vue",
				"yaml",
			},
		},
		dependencies = {
			"windwp/nvim-ts-autotag",
			"RRethy/nvim-treesitter-endwise",
			"JoosepAlviste/nvim-ts-context-commentstring",
		},
		config = function(_, opts)
			require("nvim-treesitter.configs").setup(opts)

			vim.treesitter.language.register("twig", "html.twig")
		end,
	},
}
