#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SEPARATOR=" "
WIDTH=$(tmux display -p "#{client_width}")
SHOULD_DISPLAY=true

function join { local d=$1; shift; echo -n "$1"; shift; printf "%s" "${@/#/$d}"; }
function usage {
  cat << EOF
Usage: ${0##*/} [-h] [-s SEPARATOR] -w WIDGET
Get tmux status line WIDGET

  -h            display this help and exit
  -s SEPARATOR  a separator to user between each widget
  -w WIDGET     return the tmux status line WIDGET
EOF
}

OPTIND=1
while getopts "h?s:w:" opt; do
  case "$opt" in
    h|\?)
      usage
      exit 0
      ;;
    s)
      SEPARATOR="$OPTARG"
      ;;
    w)
      WIDGETS+=("$OPTARG")
      ;;
  esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

if [[ ${#WIDGETS[@]} -eq 0 ]]; then
  usage
  exit
fi

for WIDGET in "${WIDGETS[@]}"; do
  . $DIR/widget/$WIDGET

  if [[ $(type -t widget_should_display) == function ]]; then
    SHOULD_DISPLAY=$(widget_should_display)
  fi

  WIDGET_OUTPUT=$(widget)

  [[ $SHOULD_DISPLAY = true ]] && OUTPUT+=("$WIDGET_OUTPUT")
done

join "#[default]$SEPARATOR" "${OUTPUT[@]}"
